### ISSUE TITLE
Errors while using the recasting scripts

### ISSUE THREAD

**Issue by patuchen** [sidsvash26/temporal_nli#2]
Hello,

I tried to run the recasting scripts as in the instructions and ran into several problems:

The first was not being to replicate the virtual environment using the command `pipenv install --ignore-pipfile` in the root folder of the cloned repo.
I got the following error:

`[pipenv.exceptions.InstallError]: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
[pipenv.exceptions.InstallError]:     predpatt from http://github.com/hltcoe/PredPatt/tarball/master#egg=predpatt (from -r /tmp/pipenv-7ofmgoub-requirements/pipenv-6a86b_d8-requirement.txt (line 1)):
[pipenv.exceptions.InstallError]:         Expected sha256 3a8d83919a7da1a8b1ceff006189e9016be9a4380e0972f7e6432e46f6204792
[pipenv.exceptions.InstallError]:              Got        5eddad25bfb3ab061e4dcd1c7db7c5b4cc0a745dc0bd59c0939500828068afeb
ERROR: Couldn't install package: predpatt`

I resolved this by creating a new virtual environment and installing the requirements by `pip3 install -r requirements.txt `, all of the packages were installed successfully with the given versions.

I had no trouble downloading the source corpora. The recasting scripts went smoothly until "data_loader_red.py", which failed on the line `red_all_df = red_all_df[columns]` with this error message: 
`KeyError: "['docid' 'extrainfo' 'eventInstanceID' 'relatedToEventInstance' 'relation'\n 'eid1_text' 'eid2_text' 'eid1_POS' 'eid2_POS' 'eid1_lemma' 'eid2_lemma'\n 'eid1_sent_id' 'eid1_token_id' 'eid2_sent_id' 'eid2_token_id'\n 'eid1_sentence' 'eid2_sentence' 'eid1_sent_conllu' 'eid2_sent_conllu'] not in index"`

Unsurprisingly, this then led to "FileNotFound" errors in the later scripts in the pipeline.

Will you be able to help me with this?

Thank you in advance,
Patricia

**Comment by sidsvash26** [comment]
I looked at the `pipenv.lock` issue and apparently it's caused due to a recent change in the `PredPatt` package. I'll update the lock file soon. Thanks for catching that. Glad that you were able to replicate the env using `requirements.txt` file. 

About the missing files, it looks like you don't have the original RED dataset inside `data/raw_data/red/`. As mentioned on our [data](https://github.com/sidsvash26/temporal_nli/tree/main/data) page, there is no publicly available link for downloading RED corpus, hence, it is not downloaded from the `download_data.sh` provided in our repo. The bash script only creates an empty directory -- `data/raw_data/red`  inside which you **manually** need to copy the RED corpus files obtained from LDC. The [LDC link](https://catalog.ldc.upenn.edu/LDC2016T23) is already provided on the data page. 

This is how the dir structure inside  `data/raw_data/red` looks like after you have copied the corpus correctly from RED LDC :
```
ls data/raw_data/red
data  docs  index.html
```

Once you have copied the RED corpus directories inside `data/raw_data/red/`, the recasting script will work fine.

I'll make this point clearer in the documentation. 

Let me know if this solves your issue.

**Comment by patuchen** [comment]
Hello,

the problem was indeed in the missing RED corpus. Since the RED corpus is so expensive, I instead commented out the scripts and lines that process it and everything went well.

Thank you for your help!

**Comment by sidsvash26** [comment]
Sure. You might be able to get RED through a university LDC license. That's how I got it. 
Closing the issue as your problem seems solved.
